### ISSUE TITLE
Make naming less haskell-y

### ISSUE THREAD

**Issue by kurtschelfthout** [stijnmoreels/FsCheck.Extras#2]
F# doesn't allow the backtick to make functions infix, so the current naming scheme doesn't quite work out in F#.

E.g. `a inverts b` reads nicely, `inverts a b` not so much. Naming along the lines of `areInverses a b` sounds more idiomatic to me.

Also many people in the F# community don't like operators. (I'm not one of them - though good operator names are hard - but mind your audience...)

**Comment by stijnmoreels** [comment]
`b |> inverts a` ?

**Comment by kurtschelfthout** [comment]
Yeah...only works when the arguments are not order-dependent though.

**Comment by stijnmoreels** [comment]
See PR: #6
